export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './styles/reset.css';
import './styles/common.css';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
